# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('precription', models.CharField(max_length=150)),
                ('age', models.IntegerField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_admission', models.DateField()),
                ('dateofdischarge', models.DateField()),
                ('risk_score', models.CharField(max_length=50)),
                ('enrolled_program', models.CharField(max_length=20)),
                ('doctor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_desc', models.CharField(max_length=150)),
                ('doctor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('contact', models.IntegerField(primary_key=True, serialize=False)),
                ('specialisation', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='problem',
            field=models.ManyToManyField(to='consumer.Problem'),
        ),
    ]
